services:
  app:
    build:
      context: .
      secrets:
        - github_token
      ssh:
        - default
    image: skrib:latest
    volumes:
      # Mount backend for development hot-reload
      - ./backend:/app
      # Mount frontend for development hot-reload
      - ./frontend:/frontend
      # Mount database to persist data
      - ./data:/data
      # Allow us to map in /tmp
      - "${BITBUCKET_CLONE_DIR:-/tmp}:/tmp"
    environment:
      - PYTHONUNBUFFERED=1
    init: true
    entrypoint: ""
    ports:
      - "8000:8000"  # Running via "localhost" is a secure context so we can test Service Workers
    command:
      - sh
      - -c
      - |
        npm run dev -- --host &
        cd /app && python -m uvicorn skrib.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  caddy_data:
  caddy_config:

secrets:
  github_token:
    environment: GITHUB_TOKEN
