[project]
name = "skrib"
version = "0.0.1"
authors = [
    { name = "Seth Miller", email = "seth@four43.com" }
]
readme = "README.md"
requires-python = ">=3.12"

keywords = [""]

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "python-multipart",
    "requests",
    "pywebpush",
    "py-vapid",
    "Pillow",
]

[project.optional-dependencies]
dev = [
    "pytest~=9.0",
    "pytest-cov",
    "httpx",
]

[tool.setuptools.packages.find]
include = ["skrib*"]

[tool.xwe_build]
modules = [
    "skrib",
    "tests",
]
